-- ============================================================================
-- Ticket Booking System - required deltas on top of 01_schema.sql
--
-- HOW TO RUN: execute this in the Supabase SQL Editor AFTER 01_schema.sql.
-- This script is idempotent - running it twice is harmless.
--
-- WHY THESE CHANGES ARE NECESSARY
--
-- 1. Seat locking needs ownership + an expiry instant.
--    The base schema has an event_seats.status of 'LOCKED' but no way to record
--    WHO holds the lock or WHEN it lapses, so a lock could never be released.
--    We hold seats for 24 hours (see app.hold.ttlHours in application.conf).
--
-- 2. booking_seats.event_seat_id UNIQUE breaks cancel-then-rebook.
--    Cancelling a booking returns its seats to 'AVAILABLE', but the original
--    booking_seats row still occupies that event_seat_id, so the next booking of
--    the same seat would violate the constraint. Replacing it with a UNIQUE index
--    restricted to ACTIVE rows keeps the database-level double-booking guarantee
--    (at most one active claim per seat) while allowing the seat to be sold again
--    and preserving cancelled rows as history.
--
-- 3. TIMESTAMPTZ, not TIMESTAMP, for the new time columns.
--    A 24-hour deadline compared against now() in a timezone-naive column is
--    ambiguous and would expire holds at the wrong moment.
-- ============================================================================

-- --- 1. Lock ownership + expiry -------------------------------------------
ALTER TABLE event_seats
    ADD COLUMN IF NOT EXISTS locked_by       UUID REFERENCES users(id),
    ADD COLUMN IF NOT EXISTS lock_expires_at TIMESTAMPTZ;

-- Lets the expiry sweeper find stale locks without scanning the whole table.
CREATE INDEX IF NOT EXISTS idx_event_seats_lock_expiry
    ON event_seats (lock_expires_at) WHERE status = 'LOCKED';

-- --- 2. Hold expiry on the PENDING booking --------------------------------
ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS hold_expires_at TIMESTAMPTZ;

-- --- 3. Active-claim flag on booking_seats --------------------------------
ALTER TABLE booking_seats
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

-- Drop the plain UNIQUE(event_seat_id) constraint. The constraint name is
-- generated by Postgres, so look it up rather than assuming 'booking_seats_event_seat_id_key'.
DO $$
DECLARE
    target_constraint text;
    col_attnum        smallint;
BEGIN
    SELECT attnum INTO col_attnum
    FROM pg_attribute
    WHERE attrelid = 'booking_seats'::regclass
      AND attname = 'event_seat_id'
      AND NOT attisdropped;

    SELECT conname INTO target_constraint
    FROM pg_constraint
    WHERE conrelid = 'booking_seats'::regclass
      AND contype = 'u'
      AND conkey = ARRAY[col_attnum];

    IF target_constraint IS NOT NULL THEN
        EXECUTE format('ALTER TABLE booking_seats DROP CONSTRAINT %I', target_constraint);
        RAISE NOTICE 'Dropped plain unique constraint %', target_constraint;
    ELSE
        RAISE NOTICE 'No plain UNIQUE(event_seat_id) constraint found - nothing to drop';
    END IF;
END $$;

-- THE double-booking guarantee: at most one ACTIVE booking_seats row per seat.
-- Two concurrent transactions claiming the same seat -> one commits, one fails here.
CREATE UNIQUE INDEX IF NOT EXISTS uq_booking_seats_active
    ON booking_seats (event_seat_id) WHERE is_active;

-- --- Helpful supporting indexes -------------------------------------------
CREATE INDEX IF NOT EXISTS idx_event_seats_event      ON event_seats (event_id);
CREATE INDEX IF NOT EXISTS idx_events_start_time      ON events (start_time);
CREATE INDEX IF NOT EXISTS idx_events_status          ON events (status);
CREATE INDEX IF NOT EXISTS idx_bookings_user          ON bookings (user_id);
CREATE INDEX IF NOT EXISTS idx_bookings_event         ON bookings (event_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status        ON bookings (status);
CREATE INDEX IF NOT EXISTS idx_booking_seats_booking  ON booking_seats (booking_id);
CREATE INDEX IF NOT EXISTS idx_seats_venue            ON seats (venue_id);

-- --- Verification ---------------------------------------------------------
-- Should return 7 rows: bookings, booking_seats, event_seats, events, seats, users, venues
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('users','venues','seats','events','event_seats','bookings','booking_seats')
ORDER BY table_name;
